CREATE TABLE PRODUCT(
  PRODUCT_ID BIGSERIAL PRIMARY KEY,
  NAME VARCHAR(35) NOT NULL,
  PRICE INTEGER NOT NULL,
  TYPE VARCHAR(15)
);

CREATE TABLE STORE_USER(
  USER_ID BIGSERIAL PRIMARY KEY,
  USER_TYPE VARCHAR(15) NOT NULL,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  EMAIL_ADDRESS VARCHAR(64),
  PHONE_NUMBER VARCHAR(24)
);